### ISSUE TITLE
Running process got stuck 

### ISSUE THREAD

**Issue by TrololoLi** [elementary-data/elementary-lineage#39]
Hi team,
I tried to run elementary, but it just got stuck after logging into Snowflake.
Nothing has changed on my screen at least for an hour.
![image](https://user-images.githubusercontent.com/14012678/148933828-b6e60c4c-403a-49ee-af2d-4b8ee876fa7c.png)

Do you have any ideas about what could go wrong?

**Comment by TrololoLi** [comment]
After 1.5 hour it has finished. Can you add logging during the process as well? Then a user can understand that something is going on=)
![image](https://user-images.githubusercontent.com/14012678/148935602-16ca01b4-9b84-4620-8f92-af31a6ea3115.png)

**Comment by oravi** [comment]
Hi @TrololoLi! thank you so much for posting this issue. 

This is the reason why we added those progress bars so you can track the progress while the tool extracts queries, parses them and then updates the lineage graph. 

Did you not see the progress bars while waiting for the result? if so, we could definitely add more visibility there.

We would love also to learn how to improve performance, would you be willing to join our [community on Slack](https://join.slack.com/t/elementary-community/shared_invite/zt-uehfrq2f-zXeVTtXrjYRbdE_V6xq4Rg) so we can learn more there?

**Comment by TrololoLi** [comment]
I will join your slack. Thanks a lot!
Unfortunately, I got the progress bar somewhere in the end of the job run. It was running most of the time without the bar.

**Comment by oravi** [comment]
HI @TrololoLi,
Based on this issue we added new interactive logs and live spinners so the user can understand now the steps that are running. This is already live with our newest version (0.1.0) and onwards.

Thanks again for reporting this! 
Closing this issue for now, feel free to re-open if it's not working as expected.
