### ISSUE TITLE
Move schema and/or database definition from profiles.yml to CLI

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary-lineage#41]
Today the database and schema for the lineage graph are defined in a yml file. 
These are used for both the connection and the filtering of the graph/queries. 
The change is to get these as input in the CLI. 

Pros:
Would enable easier workflows creation for different datasets using the same configuration file.

Cons:
Change from how these are used in dbt, whic is familiar to the users.

**Comment by oravi** [comment]
This is live in our newest version (0.1.0) and onwards.  Closing this issue, thanks!
